### ISSUE TITLE
after ISTFT, the audio is not the same as original

### ISSUE THREAD

**Issue by iamhankai** [audiolabs/python_stft#4]
import stft
    import scipy.io.wavfile as wav

    fs, audio = wav.read('input.wav')
    specgram = stft.spectrogram(audio)
    output = stft.ispectrogram(specgram)
    wav.write('input-anchor.wav', fs, output)
- - -
'input-anchor.wav' sounds not like 'input.wav' at all.

**Comment by nils-werner** [comment]
I cannot reproduce this and there are unittests in place that ensure this identity. Maybe it's your WAV file, can you check with another file or provide the WAV file your're using?

**Comment by iamhankai** [comment]
I have modified the code, it works:)
